/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_s5r_android_signal_TestActivity */

#ifndef _Included_jp_s5r_android_signal_TestActivity
#define _Included_jp_s5r_android_signal_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_s5r_android_signal_TestActivity
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_s5r_android_signal_TestActivity_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
